id = "gruber-darker"
name = "Gruber Darker"
version = "0.0.7"
schema_version = 1
authors = ["Thomas Jensen <thomas.jensen_@outlook.com>"]
description = "A port of the Gruber Darker theme for emacs"
repository = "https://github.com/th0jensen/gruber-darker.zed"
